spring:
  application:
    name: edi-conv


server:
  port: 8085   # The port your microservice will run on
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG





management:
  endpoints:
    web:
      exposure:
        include: health,info

